package com.jbk.entity;
// Generated Aug 19, 2020 8:13:22 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "springmvc")
public class Subject implements java.io.Serializable {

	private Integer subId;
	private String subName;
	//private Set students = new HashSet(0);

	public Subject() {
	}

	public Subject(String subName) {
		this.subName = subName;
	}

	/*public Subject(String subName, Set students) {
		this.subName = subName;
		this.students = students;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sub_id", unique = true, nullable = false)
	public Integer getSubId() {
		return this.subId;
	}

	public void setSubId(Integer subId) {
		this.subId = subId;
	}

	@Column(name = "sub_name", nullable = false, length = 45)
	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}*/

}
